import sqlite3
db = sqlite3.connect(r'k24_shadow.db')
cur = db.cursor()
print('--- CASH/BANK ---')
cur.execute("SELECT name, parent, closing_balance FROM ledgers WHERE lower(parent) LIKE '%cash%' OR lower(parent) LIKE '%bank%'")
for r in cur.fetchall(): print(f'  {str(r[0])[:30]:30s} | {str(r[1]):25s} | {r[2] or 0:,.2f}')
print('--- DEBTORS (non-zero) ---')
cur.execute("SELECT name, closing_balance FROM ledgers WHERE lower(parent) LIKE '%debtor%' AND closing_balance != 0 ORDER BY closing_balance DESC")
for r in cur.fetchall(): print(f'  {str(r[0])[:35]:35s} | {r[1] or 0:,.2f}')
print('--- CREDITORS (non-zero) ---')
cur.execute("SELECT name, closing_balance FROM ledgers WHERE lower(parent) LIKE '%creditor%' AND closing_balance != 0 ORDER BY closing_balance DESC")
for r in cur.fetchall(): print(f'  {str(r[0])[:35]:35s} | {r[1] or 0:,.2f}')
print('--- TENANT CHECK ---')
cur.execute("SELECT tenant_id, COUNT(*) FROM ledgers GROUP BY tenant_id")
for r in cur.fetchall(): print(f'  tenant={r[0]} count={r[1]}')
db.close()
