"""add_tenant_mixin

Revision ID: 26fa825b5d50
Revises: 
Create Date: 2025-12-08 01:31:56.974789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26fa825b5d50'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:




    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.exc import OperationalError
    from sqlalchemy import inspect
    
    bind = op.get_bind()
    inspector = inspect(bind)

    def safe_add_tenant(table_name):
        try:
            op.add_column(table_name, sa.Column('tenant_id', sa.String(), nullable=True))
        except OperationalError:
            # Column likely exists
            pass

    def safe_create_index(batch_op, index_name, table_name, columns, **kwargs):
        # Check if index exists using inspector
        indexes = inspector.get_indexes(table_name)
        existing_names = [idx['name'] for idx in indexes]
        if index_name not in existing_names:
            batch_op.create_index(op.f(index_name), columns, **kwargs)

    # 1. audit_logs
    safe_add_tenant('audit_logs')
    op.execute("UPDATE audit_logs SET tenant_id = 'default_dev_tenant' WHERE tenant_id IS NULL")
    with op.batch_alter_table('audit_logs') as batch_op:
        batch_op.alter_column('tenant_id', nullable=False)
        safe_create_index(batch_op, 'ix_audit_logs_tenant_id', 'audit_logs', ['tenant_id'], unique=False)
    
    # 2. bills
    safe_add_tenant('bills')
    op.execute("UPDATE bills SET tenant_id = 'default_dev_tenant' WHERE tenant_id IS NULL")
    with op.batch_alter_table('bills') as batch_op:
        batch_op.alter_column('tenant_id', nullable=False)
        safe_create_index(batch_op, 'ix_bills_tenant_id', 'bills', ['tenant_id'], unique=False)
        # SKIPPED: Cannot drop unnamed constraint in SQLite batch mode without name
        # batch_op.drop_constraint(None, type_='foreignkey')
    
    # 3. companies
    safe_add_tenant('companies')
    op.execute("UPDATE companies SET tenant_id = 'default_dev_tenant' WHERE tenant_id IS NULL")
    with op.batch_alter_table('companies') as batch_op:
        batch_op.alter_column('tenant_id', nullable=False)
        
        existing_indexes = [i['name'] for i in inspector.get_indexes('companies')]
        if 'ix_companies_name' in existing_indexes:
             batch_op.drop_index('ix_companies_name')
        
        safe_create_index(batch_op, 'ix_companies_name', 'companies', ['name'], unique=False)
        safe_create_index(batch_op, 'ix_companies_tenant_id', 'companies', ['tenant_id'], unique=False)
    
    # 4. items
    safe_add_tenant('items')
    op.execute("UPDATE items SET tenant_id = 'default_dev_tenant' WHERE tenant_id IS NULL")
    with op.batch_alter_table('items') as batch_op:
        batch_op.alter_column('tenant_id', nullable=False)
        existing_indexes = [i['name'] for i in inspector.get_indexes('items')]
        if 'ix_items_name' in existing_indexes:
             batch_op.drop_index('ix_items_name')
        safe_create_index(batch_op, 'ix_items_name', 'items', ['name'], unique=False)
        safe_create_index(batch_op, 'ix_items_tenant_id', 'items', ['tenant_id'], unique=False)
    
    # 5. ledgers
    safe_add_tenant('ledgers')
    op.execute("UPDATE ledgers SET tenant_id = 'default_dev_tenant' WHERE tenant_id IS NULL")
    with op.batch_alter_table('ledgers') as batch_op:
        batch_op.alter_column('tenant_id', nullable=False)
        existing_indexes = [i['name'] for i in inspector.get_indexes('ledgers')]
        if 'ix_ledgers_name' in existing_indexes:
             batch_op.drop_index('ix_ledgers_name')
        safe_create_index(batch_op, 'ix_ledgers_name', 'ledgers', ['name'], unique=False)
        safe_create_index(batch_op, 'ix_ledgers_tenant_id', 'ledgers', ['tenant_id'], unique=False)
    
    # 6. sync_state
    safe_add_tenant('sync_state')
    op.execute("UPDATE sync_state SET tenant_id = 'default_dev_tenant' WHERE tenant_id IS NULL")
    with op.batch_alter_table('sync_state') as batch_op:
        batch_op.alter_column('tenant_id', nullable=False)
        safe_create_index(batch_op, 'ix_sync_state_tenant_id', 'sync_state', ['tenant_id'], unique=False)
    
    # 7. user_settings
    safe_add_tenant('user_settings')
    op.execute("UPDATE user_settings SET tenant_id = 'default_dev_tenant' WHERE tenant_id IS NULL")
    with op.batch_alter_table('user_settings') as batch_op:
        batch_op.alter_column('tenant_id', nullable=False)
        safe_create_index(batch_op, 'ix_user_settings_tenant_id', 'user_settings', ['tenant_id'], unique=False)
    
    # 8. users
    safe_add_tenant('users')
    op.execute("UPDATE users SET tenant_id = 'default_dev_tenant' WHERE tenant_id IS NULL")
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('tenant_id', nullable=False)
        
        existing_indexes = [i['name'] for i in inspector.get_indexes('users')]
        if 'ix_users_email' in existing_indexes:
             batch_op.drop_index('ix_users_email')
        if 'ix_users_username' in existing_indexes:
             batch_op.drop_index('ix_users_username')
             
        safe_create_index(batch_op, 'ix_users_email', 'users', ['email'], unique=False)
        safe_create_index(batch_op, 'ix_users_username', 'users', ['username'], unique=False)
        safe_create_index(batch_op, 'ix_users_tenant_id', 'users', ['tenant_id'], unique=False)
    
    # 9. vouchers
    safe_add_tenant('vouchers')
    op.execute("UPDATE vouchers SET tenant_id = 'default_dev_tenant' WHERE tenant_id IS NULL")
    with op.batch_alter_table('vouchers') as batch_op:
        batch_op.alter_column('tenant_id', nullable=False)
        
        existing_indexes = [i['name'] for i in inspector.get_indexes('vouchers')]
        if 'ix_vouchers_guid' in existing_indexes:
             batch_op.drop_index('ix_vouchers_guid')
             
        safe_create_index(batch_op, 'ix_vouchers_guid', 'vouchers', ['guid'], unique=False)
        safe_create_index(batch_op, 'ix_vouchers_tenant_id', 'vouchers', ['tenant_id'], unique=False)
        # SKIPPED: Cannot drop unnamed constraint in SQLite batch mode
        # batch_op.drop_constraint(None, type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'vouchers', 'ledgers', ['party_name'], ['name'])
    op.drop_index(op.f('ix_vouchers_tenant_id'), table_name='vouchers')
    op.drop_index(op.f('ix_vouchers_guid'), table_name='vouchers')
    op.create_index('ix_vouchers_guid', 'vouchers', ['guid'], unique=1)
    op.drop_column('vouchers', 'tenant_id')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=1)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.drop_column('users', 'tenant_id')
    op.drop_index(op.f('ix_user_settings_tenant_id'), table_name='user_settings')
    op.drop_column('user_settings', 'tenant_id')
    op.drop_index(op.f('ix_sync_state_tenant_id'), table_name='sync_state')
    op.drop_column('sync_state', 'tenant_id')
    op.drop_index(op.f('ix_ledgers_tenant_id'), table_name='ledgers')
    op.drop_index(op.f('ix_ledgers_name'), table_name='ledgers')
    op.create_index('ix_ledgers_name', 'ledgers', ['name'], unique=1)
    op.drop_column('ledgers', 'tenant_id')
    op.drop_index(op.f('ix_items_tenant_id'), table_name='items')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.create_index('ix_items_name', 'items', ['name'], unique=1)
    op.drop_column('items', 'tenant_id')
    op.drop_index(op.f('ix_companies_tenant_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_index('ix_companies_name', 'companies', ['name'], unique=1)
    op.drop_column('companies', 'tenant_id')
    op.create_foreign_key(None, 'bills', 'ledgers', ['party_name'], ['name'])
    op.drop_index(op.f('ix_bills_tenant_id'), table_name='bills')
    op.drop_column('bills', 'tenant_id')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'tenant_id')
    # ### end Alembic commands ###
