"""add_ledger_phone_timestamps

Revision ID: cdb3d3aef16a
Revises: 26fa825b5d50
Create Date: 2025-12-09 18:48:18.520136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdb3d3aef16a'
down_revision: Union[str, None] = '26fa825b5d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'bills', type_='foreignkey')
    # op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    # op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    
    # Use batch op for safety, though add_column works on sqlite
    with op.batch_alter_table('ledgers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        # batch_op.create_index(batch_op.f('ix_ledgers_name'), ['name'], unique=False)

    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # op.create_index(op.f('ix_vouchers_guid'), 'vouchers', ['guid'], unique=False)
    # op.drop_constraint(None, 'vouchers', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'vouchers', 'ledgers', ['party_name'], ['name'])
    op.drop_index(op.f('ix_vouchers_guid'), table_name='vouchers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_ledgers_name'), table_name='ledgers')
    op.drop_column('ledgers', 'updated_at')
    op.drop_column('ledgers', 'created_at')
    op.drop_column('ledgers', 'phone')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_foreign_key(None, 'bills', 'ledgers', ['party_name'], ['name'])
    # ### end Alembic commands ###
