"""
backend/utils/report_template.py

Shared base template for K24 PDF and Excel report generation.
No FastAPI / database imports — pure reportlab + openpyxl.

Design spec:
  PDF:
    Page:    A4 portrait, 20mm margins
    Font:    Helvetica (built-in, no custom loading)
    Colors:  Text #111827 | Accent #4F46E5 | Header bg #F3F4F6
             Alt row #F9FAFB | Closing row #E5E7EB | Grid #E5E7EB
    Header:  Company left, report title right — repeats every page
    Footer:  Generated by WeAre | Computer generated | Page X of Y

  Excel:
    Font:    Calibri 10pt
    Header:  #F3F4F6 fill, bold, centered
    Alt:     white / #F9FAFB
    Numbers: Indian accounting format
    Freeze:  top data row (row 4)
    Meta:    Row 1 company+report, Row 2 period, Row 3 empty, Row 4 headers

All public functions return bytes.
"""
from __future__ import annotations

import io
import re
from datetime import datetime
from typing import List, Optional

# ─── reportlab imports ────────────────────────────────────────────────────────
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas as rl_canvas

# ─── openpyxl imports ─────────────────────────────────────────────────────────
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# ══════════════════════════════════════════════════════════════════════════════
# SHARED CONSTANTS
# ══════════════════════════════════════════════════════════════════════════════

def _indian_number(val) -> str:
    """Format a number in Indian system: 1,23,456.78"""
    try:
        n = float(val)
    except (TypeError, ValueError):
        return str(val) if val else "—"
    neg = n < 0
    n = abs(n)
    int_part = int(n)
    frac = f"{n - int_part:.2f}"[1:]  # ".XX"
    s = str(int_part)
    if len(s) <= 3:
        formatted = s
    else:
        last3 = s[-3:]
        rest = s[:-3]
        groups = []
        while len(rest) > 2:
            groups.append(rest[-2:])
            rest = rest[:-2]
        if rest:
            groups.append(rest)
        groups.reverse()
        formatted = ",".join(groups) + "," + last3
    return ("-" if neg else "") + formatted + frac


# ══════════════════════════════════════════════════════════════════════════════
# PDF BASE
# ══════════════════════════════════════════════════════════════════════════════

# Page setup
_W, _H = A4          # 595.28 × 841.89 pt
_LM = 20 * mm        # left margin
_RM = _W - 20 * mm   # right margin
_TM = _H - 15 * mm   # top margin
_BM = 15 * mm        # bottom margin
_CW = _RM - _LM      # content width ≈ 555 pt

# Colour palette (spec)
_C_TEXT    = colors.HexColor("#111827")
_C_ACCENT  = colors.HexColor("#4F46E5")
_C_HDR_BG  = colors.HexColor("#F3F4F6")
_C_ALT_BG  = colors.HexColor("#F9FAFB")
_C_CLOSE_BG = colors.HexColor("#E5E7EB")
_C_GRID    = colors.HexColor("#E5E7EB")
_C_MUTED   = colors.HexColor("#6B7280")
_C_HDR_BOR = colors.HexColor("#D1D5DB")
_C_OPEN_BG = colors.HexColor("#EFF6FF")
_C_SUB_BG  = colors.HexColor("#E5E7EB")   # slightly darker
_C_GREEN   = colors.HexColor("#16A34A")
_C_RED     = colors.HexColor("#DC2626")
_C_WHITE   = colors.white

# Row heights
_HDR_H = 9 * mm
_ROW_H = 7 * mm

# Rows that fit per page (approximation)
_ROWS_PER_PAGE_FIRST = 22
_ROWS_PER_PAGE_OTHER = 30


def _pdf_line(c, x1, y, x2, lw=0.4, color=_C_GRID):
    c.setStrokeColor(color)
    c.setLineWidth(lw)
    c.line(x1, y, x2, y)


def _pdf_vline(c, x, y1, y2, lw=0.4, color=_C_GRID):
    c.setStrokeColor(color)
    c.setLineWidth(lw)
    c.line(x, y1, x, y2)


def _pdf_text(c, txt, x, y, font="Helvetica", sz=9, color=_C_TEXT, align="left"):
    c.setFont(font, sz)
    c.setFillColor(color)
    s = str(txt)
    if align == "right":
        c.drawRightString(x, y, s)
    elif align == "center":
        c.drawCentredString(x, y, s)
    else:
        c.drawString(x, y, s)


def _pdf_fmt(val) -> str:
    """Format as Indian currency."""
    try:
        n = float(val)
        return _indian_number(n)
    except (TypeError, ValueError):
        return str(val) if val else "—"


def pdf_shared_header(
    c,
    company_name: str,
    company_address: str,
    gstin: str,
    pan: str,
    report_title: str,
    date_from: str,
    date_to: str,
) -> float:
    """
    Draw the shared header on the current page.
    Returns the bottom y-coordinate of the header (where content can start).

    Left:  Company name (bold 13pt) + address + GSTIN + PAN (9pt muted)
    Right: Report title (bold 14pt accent) + Period (10pt)
    Below: Horizontal divider
    """
    top = _TM

    # ── Company info (left) ──────────────────────────────────────────────────
    cy = top
    _pdf_text(c, company_name, _LM, cy, "Helvetica-Bold", 13, _C_TEXT)
    cy -= 5.5 * mm
    if company_address:
        for line in company_address.split("\n")[:2]:
            _pdf_text(c, line.strip(), _LM, cy, "Helvetica", 9, _C_MUTED)
            cy -= 4 * mm
    if gstin:
        _pdf_text(c, f"GSTIN: {gstin}", _LM, cy, "Helvetica", 9, _C_MUTED)
        cy -= 4 * mm
    if pan:
        _pdf_text(c, f"PAN: {pan}", _LM, cy, "Helvetica", 9, _C_MUTED)
        cy -= 4 * mm

    # ── Report title + period (right) ────────────────────────────────────────
    _pdf_text(c, report_title, _RM, top, "Helvetica-Bold", 14, _C_ACCENT, "right")
    period_str = f"Period: {date_from}  \u2014  {date_to}"
    _pdf_text(c, period_str, _RM, top - 5.5 * mm, "Helvetica", 10, _C_MUTED, "right")

    # ── Logo placeholder (top-right corner, 15×15mm box) ────────────────────
    # (reserved space — no image loading)

    # ── Divider ──────────────────────────────────────────────────────────────
    divider_y = min(cy, top - 5.5 * mm - 5 * mm) - 3 * mm
    _pdf_line(c, _LM, divider_y, _RM, lw=0.8, color=_C_TEXT)
    return divider_y - 3 * mm


def pdf_shared_footer(c, page: int, total_pages: int):
    """
    Draw the shared footer on the current page.
    Left: "Generated by WeAre"
    Center: "Computer generated, no signature required"
    Right: "Page X of Y"
    """
    fy = _BM + 8 * mm
    _pdf_line(c, _LM, fy, _RM, lw=0.5, color=_C_MUTED)
    _pdf_text(c, "Generated by WeAre", _LM, fy - 4.5 * mm, "Helvetica", 7.5, _C_MUTED)
    _pdf_text(c, "Computer generated, no signature required",
              _W / 2, fy - 4.5 * mm, "Helvetica", 7.5, _C_MUTED, "center")
    _pdf_text(c, f"Page {page} of {total_pages}",
              _RM, fy - 4.5 * mm, "Helvetica", 7.5, _C_MUTED, "right")


def pdf_table(
    c,
    y: float,
    headers: List[str],
    rows: List[dict],           # each dict: {"cells": [...], "row_type": ""|"opening"|"closing"|"subtotal"}
    col_widths_mm: List[float],
    col_alignments: List[str],  # "left" | "center" | "right"
) -> float:
    """
    Draw a table at position y.
    Returns the bottom y of the last row drawn.

    Row types:
      ""          → standard alternating white/#F9FAFB
      "opening"   → italic, #EFF6FF bg
      "closing"   → bold, #E5E7EB bg
      "subtotal"  → bold, slightly darker bg #D1D5DB
    """
    # Build x positions
    xs = [_LM]
    for w in col_widths_mm:
        xs.append(xs[-1] + w * mm)

    top = y
    # ── Header row ──────────────────────────────────────────────────────────
    c.setFillColor(_C_HDR_BG)
    c.rect(_LM, top - _HDR_H, _CW, _HDR_H, fill=1, stroke=0)
    _pdf_line(c, _LM, top - _HDR_H, _RM, lw=0.8, color=_C_HDR_BOR)

    for i, hdr in enumerate(headers):
        if i >= len(xs) - 1:
            break
        cell_x = xs[i]
        cell_nx = xs[i + 1]
        cell_w = cell_nx - cell_x
        align = col_alignments[i] if i < len(col_alignments) else "left"
        ty = top - _HDR_H / 2 - 2.5
        if align == "right":
            _pdf_text(c, hdr, cell_nx - 2 * mm, ty, "Helvetica-Bold", 8, _C_TEXT, "right")
        elif align == "center":
            _pdf_text(c, hdr, cell_x + cell_w / 2, ty, "Helvetica-Bold", 8, _C_TEXT, "center")
        else:
            _pdf_text(c, hdr, cell_x + 2 * mm, ty, "Helvetica-Bold", 8, _C_TEXT)

    cur_y = top - _HDR_H
    alt_counter = 0  # only counts non-special rows

    # ── Data rows ────────────────────────────────────────────────────────────
    for row_dict in rows:
        cells = row_dict.get("cells", [])
        rt = row_dict.get("row_type", "")

        # Background
        if rt == "opening":
            c.setFillColor(_C_OPEN_BG)
            c.rect(_LM, cur_y - _ROW_H, _CW, _ROW_H, fill=1, stroke=0)
        elif rt == "closing":
            c.setFillColor(_C_CLOSE_BG)
            c.rect(_LM, cur_y - _ROW_H, _CW, _ROW_H, fill=1, stroke=0)
        elif rt == "subtotal":
            c.setFillColor(colors.HexColor("#D1D5DB"))
            c.rect(_LM, cur_y - _ROW_H, _CW, _ROW_H, fill=1, stroke=0)
        else:
            if alt_counter % 2 == 1:
                c.setFillColor(_C_ALT_BG)
                c.rect(_LM, cur_y - _ROW_H, _CW, _ROW_H, fill=1, stroke=0)
            alt_counter += 1

        # Grid line
        _pdf_line(c, _LM, cur_y - _ROW_H, _RM, lw=0.3, color=_C_GRID)

        # Choose font/style per row_type
        if rt in ("closing", "subtotal"):
            fn = "Helvetica-Bold"
        elif rt == "opening":
            fn = "Helvetica-Oblique"
        else:
            fn = "Helvetica"

        for ci, cell_val in enumerate(cells):
            if ci >= len(xs) - 1:
                break
            cell_x = xs[ci]
            cell_nx = xs[ci + 1]
            cell_w = cell_nx - cell_x
            align = col_alignments[ci] if ci < len(col_alignments) else "left"
            tv = str(cell_val) if cell_val is not None else ""
            ty = cur_y - _ROW_H / 2 - 2.5

            if align == "right":
                _pdf_text(c, tv, cell_nx - 2 * mm, ty, fn, 8, _C_TEXT, "right")
            elif align == "center":
                _pdf_text(c, tv, cell_x + cell_w / 2, ty, fn, 8, _C_TEXT, "center")
            else:
                _pdf_text(c, tv, cell_x + 2 * mm, ty, fn, 8, _C_TEXT)

        cur_y -= _ROW_H

    # Outer border + column dividers
    c.setStrokeColor(_C_GRID)
    c.setLineWidth(0.5)
    c.rect(_LM, cur_y, _CW, top - cur_y, fill=0, stroke=1)
    for xi in xs[1:-1]:
        _pdf_vline(c, xi, cur_y, top, lw=0.3, color=_C_GRID)

    return cur_y


def pdf_build_pages(
    company_name: str,
    company_address: str,
    gstin: str,
    pan: str,
    report_title: str,
    date_from: str,
    date_to: str,
    headers: List[str],
    all_rows: List[dict],
    col_widths_mm: List[float],
    col_alignments: List[str],
) -> bytes:
    """
    Full PDF: header, paginated table, footer on every page.
    Returns raw PDF bytes.
    """
    # Paginate
    pages: List[List[dict]] = []
    remaining = list(all_rows)
    pages.append(remaining[:_ROWS_PER_PAGE_FIRST])
    remaining = remaining[_ROWS_PER_PAGE_FIRST:]
    while remaining:
        pages.append(remaining[:_ROWS_PER_PAGE_OTHER])
        remaining = remaining[_ROWS_PER_PAGE_OTHER:]
    if not pages:
        pages = [[]]

    total_pages = len(pages)
    buf = io.BytesIO()
    c = rl_canvas.Canvas(buf, pagesize=A4)

    for page_num, page_rows in enumerate(pages, 1):
        y = pdf_shared_header(
            c, company_name, company_address, gstin, pan,
            report_title, date_from, date_to
        )
        y = pdf_table(c, y, headers, page_rows, col_widths_mm, col_alignments)
        pdf_shared_footer(c, page_num, total_pages)
        if page_num < total_pages:
            c.showPage()

    c.save()
    buf.seek(0)
    return buf.read()


# ══════════════════════════════════════════════════════════════════════════════
# EXCEL BASE
# ══════════════════════════════════════════════════════════════════════════════

# Style constants
_XL_HDR_FILL  = PatternFill(start_color="F3F4F6", end_color="F3F4F6", fill_type="solid")
_XL_ALT_FILL  = PatternFill(start_color="F9FAFB", end_color="F9FAFB", fill_type="solid")
_XL_TITLE_FILL = PatternFill(start_color="4F46E5", end_color="4F46E5", fill_type="solid")
_XL_CLOSE_FILL = PatternFill(start_color="E5E7EB", end_color="E5E7EB", fill_type="solid")
_XL_OPEN_FILL  = PatternFill(start_color="EFF6FF", end_color="EFF6FF", fill_type="solid")
_XL_SUB_FILL   = PatternFill(start_color="D1D5DB", end_color="D1D5DB", fill_type="solid")

_XL_FONT_BASE    = lambda bold=False: Font(name="Calibri", size=10, bold=bold)
_XL_FONT_TITLE   = Font(name="Calibri", size=12, bold=True, color="FFFFFF")
_XL_FONT_MUTED   = Font(name="Calibri", size=10, color="6B7280")
_XL_FONT_ACCENT  = Font(name="Calibri", size=12, bold=True, color="4F46E5")

_XL_ALIGN_CENTER = Alignment(horizontal="center", vertical="center", wrap_text=True)
_XL_ALIGN_LEFT   = Alignment(horizontal="left",   vertical="center", wrap_text=True)
_XL_ALIGN_RIGHT  = Alignment(horizontal="right",  vertical="center")

_XL_THIN_BORDER = Border(
    bottom=Side(style="thin", color="E5E7EB"),
    top=Side(style="thin", color="E5E7EB"),
)

_XL_NUM_FMT = '#,##0.00'          # Indian-style (openpyxl uses this directly)
_XL_NUM_FMT_IND = '[\u20b9-4009]#,##,##0.00'  # with ₹ symbol


def _xl_write_meta(ws, col_count: int, company_name: str, report_name: str, period: str):
    """
    Write the 4-row preamble:
      Row 1: Company name + report name (merged, bold 12pt accent)
      Row 2: Period + generated timestamp (merged, muted 10pt)
      Row 3: Empty
      Row 4: Column headers (written by caller)
    """
    last_col = get_column_letter(col_count)

    # Row 1 — Company + report title
    ws.merge_cells(f"A1:{last_col}1")
    cell_r1 = ws["A1"]
    cell_r1.value = f"{company_name}  |  {report_name}"
    cell_r1.font  = _XL_FONT_ACCENT
    cell_r1.fill  = PatternFill(start_color="F3F4F6", end_color="F3F4F6", fill_type="solid")
    cell_r1.alignment = _XL_ALIGN_LEFT
    ws.row_dimensions[1].height = 22

    # Row 2 — Period
    ws.merge_cells(f"A2:{last_col}2")
    cell_r2 = ws["A2"]
    cell_r2.value = f"Period: {period}    |    Generated: {datetime.now().strftime('%d-%b-%Y %I:%M %p')}"
    cell_r2.font  = _XL_FONT_MUTED
    cell_r2.alignment = _XL_ALIGN_LEFT
    ws.row_dimensions[2].height = 17

    # Row 3 — blank spacer
    ws.row_dimensions[3].height = 8

    ws.row_dimensions[4].height = 20  # header row height


def _xl_write_headers(ws, headers: List[str], alignments: List[str], row: int = 4):
    """Write the header row with #F3F4F6 fill, bold, aligned."""
    for ci, hdr in enumerate(headers, 1):
        cell = ws.cell(row=row, column=ci, value=hdr)
        cell.fill      = _XL_HDR_FILL
        cell.font      = _XL_FONT_BASE(bold=True)
        cell.alignment = _XL_ALIGN_CENTER
        cell.border    = _XL_THIN_BORDER


def _xl_write_rows(
    ws,
    data_rows: List[dict],  # {"cells": [...], "row_type": ""|"opening"|"closing"|"subtotal", "numeric_cols": set}
    alignments: List[str],
    start_row: int = 5,
):
    """Write data rows with alternating fill, number formatting, row_type styling."""
    alt_counter = 0
    for ri, row_dict in enumerate(data_rows):
        cells     = row_dict.get("cells", [])
        rt        = row_dict.get("row_type", "")
        num_cols  = row_dict.get("numeric_cols", set())  # 0-indexed set of columns that are numbers
        row_num   = start_row + ri

        # Choose fill
        if rt == "opening":
            fill = _XL_OPEN_FILL
        elif rt == "closing":
            fill = _XL_CLOSE_FILL
        elif rt == "subtotal":
            fill = _XL_SUB_FILL
        else:
            fill = _XL_ALT_FILL if (alt_counter % 2 == 1) else None
            alt_counter += 1

        bold = rt in ("closing", "subtotal")
        italic = rt == "opening"

        for ci, val in enumerate(cells, 1):
            cell = ws.cell(row=row_num, column=ci, value=val)
            if fill:
                cell.fill = fill
            cell.font = Font(name="Calibri", size=10, bold=bold, italic=italic)
            cell.border = _XL_THIN_BORDER

            col_align = alignments[ci - 1] if (ci - 1) < len(alignments) else "left"
            if col_align == "right":
                cell.alignment = _XL_ALIGN_RIGHT
                if isinstance(val, (int, float)):
                    cell.number_format = _XL_NUM_FMT
            elif col_align == "center":
                cell.alignment = _XL_ALIGN_CENTER
            else:
                cell.alignment = _XL_ALIGN_LEFT

        ws.row_dimensions[row_num].height = 16


def _xl_auto_width(ws, headers: List[str], data_rows: List[dict]):
    """Auto-fit column widths based on content."""
    col_widths = [max(len(str(h)), 8) for h in headers]
    for row_dict in data_rows:
        for ci, val in enumerate(row_dict.get("cells", [])):
            if ci < len(col_widths):
                col_widths[ci] = max(col_widths[ci], min(len(str(val or "")), 40))
    for ci, width in enumerate(col_widths, 1):
        ws.column_dimensions[get_column_letter(ci)].width = width + 3


def excel_build_workbook(
    company_name: str,
    report_name: str,
    period: str,
    headers: List[str],
    data_rows: List[dict],    # list of {"cells": [...], "row_type": "", "numeric_cols": set}
    col_alignments: List[str],
    sheet_name: str = "Report",
) -> bytes:
    """
    Build a styled XLSX workbook and return raw bytes.
    Sheet structure:
      Row 1: Company + report title (merged, accent)
      Row 2: Period (merged, muted)
      Row 3: empty
      Row 4: headers (#F3F4F6, bold)
      Row 5+: data
    Top data row (row 4 headers) is frozen.
    """
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = sheet_name[:31]

    col_count = max(len(headers), 1)
    _xl_write_meta(ws, col_count, company_name, report_name, period)
    _xl_write_headers(ws, headers, col_alignments, row=4)
    _xl_write_rows(ws, data_rows, col_alignments, start_row=5)
    _xl_auto_width(ws, headers, data_rows)

    # Freeze row 4 (freeze below header at row 5)
    ws.freeze_panes = "A5"

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf.read()


# ══════════════════════════════════════════════════════════════════════════════
# 5 REPORT TEMPLATES — PDF
# ══════════════════════════════════════════════════════════════════════════════

def generate_ledger_pdf(
    data: dict,
    company_info: dict,
    date_from: str,
    date_to: str,
) -> bytes:
    """
    Ledger Statement PDF.
    Columns: Date | Particulars | Voucher Type | Voucher No | Debit (₹) | Credit (₹) | Balance (₹)
    Special rows: opening_row → opening style, closing_row → closing style.
    data keys: company (str), gstin (str), rows (list of dicts), opening_balance (float)
    """
    cn   = company_info.get("name", data.get("company", "Your Company"))
    addr = company_info.get("address", data.get("address", ""))
    gstin = company_info.get("gstin", data.get("gstin", ""))
    pan   = company_info.get("pan", data.get("pan", ""))

    headers = ["Date", "Particulars", "Voucher Type", "Voucher No", "Debit (₹)", "Credit (₹)", "Balance (₹)"]
    widths  = [20, 45, 28, 25, 22, 22, 25]   # mm — total ≈ 187mm ≈ 530pt
    aligns  = ["center", "left", "left", "center", "right", "right", "right"]

    all_rows: List[dict] = []

    # Opening balance row
    ob = data.get("opening_balance", 0.0)
    all_rows.append({
        "cells": ["", "Opening Balance", "", "", "", "", _indian_number(ob)],
        "row_type": "opening",
    })

    # Ledger rows
    balance = ob
    for r in data.get("rows", []):
        dr = r.get("debit", 0.0) or 0.0
        cr = r.get("credit", 0.0) or 0.0
        balance += dr - cr
        all_rows.append({
            "cells": [
                r.get("date", ""),
                r.get("particulars", r.get("party_name", "")),
                r.get("voucher_type", ""),
                r.get("voucher_no", r.get("voucher_number", "")),
                _indian_number(dr) if dr else "—",
                _indian_number(cr) if cr else "—",
                _indian_number(balance),
            ],
            "row_type": "",
        })

    # Closing balance row
    all_rows.append({
        "cells": ["", "Closing Balance", "", "", "", "", _indian_number(balance)],
        "row_type": "closing",
    })

    return pdf_build_pages(
        cn, addr, gstin, pan, "Ledger Statement", date_from, date_to,
        headers, all_rows, widths, aligns,
    )


def generate_balance_sheet_pdf(
    data: dict,
    company_info: dict,
    date_from: str,
    date_to: str,
) -> bytes:
    """
    Balance Sheet PDF.
    Two-section: Assets (numbered) then Liabilities (numbered) in same table.
    Bottom: Total Assets = Total Equity & Liabilities in bold accent.
    data keys: assets (list), liabilities (list), total_assets (float), total_liabilities (float)
    """
    cn    = company_info.get("name", "Your Company")
    addr  = company_info.get("address", "")
    gstin = company_info.get("gstin", "")
    pan   = company_info.get("pan", "")

    headers = ["#", "Ledger / Group", "Section", "Amount (₹)"]
    widths  = [10, 110, 42, 35]   # total ≈ 197mm
    aligns  = ["center", "left", "left", "right"]

    all_rows: List[dict] = []

    # Assets section
    all_rows.append({"cells": ["", "ASSETS", "", ""], "row_type": "subtotal"})
    asset_sections = ["Non-current Assets", "Current Assets"]
    assets = data.get("assets", [])
    for idx, item in enumerate(assets, 1):
        grp = item.get("group", "Other Assets")
        all_rows.append({
            "cells": [str(idx), item.get("name", ""), grp, _indian_number(item.get("amount", 0))],
            "row_type": "",
        })

    ta = data.get("total_assets", 0.0)
    all_rows.append({"cells": ["", "Total Assets", "", _indian_number(ta)], "row_type": "closing"})

    # Equity & Liabilities section
    all_rows.append({"cells": ["", "EQUITY & LIABILITIES", "", ""], "row_type": "subtotal"})
    liabilities = data.get("liabilities", [])
    for idx, item in enumerate(liabilities, 1):
        grp = item.get("group", "Other Liabilities")
        all_rows.append({
            "cells": [str(idx), item.get("name", ""), grp, _indian_number(item.get("amount", 0))],
            "row_type": "",
        })

    tl = data.get("total_liabilities", 0.0)
    all_rows.append({"cells": ["", "Total Equity & Liabilities", "", _indian_number(tl)], "row_type": "closing"})

    return pdf_build_pages(
        cn, addr, gstin, pan, "Balance Sheet", date_from, date_to,
        headers, all_rows, widths, aligns,
    )


def generate_profit_loss_pdf(
    data: dict,
    company_info: dict,
    date_from: str,
    date_to: str,
) -> bytes:
    """
    Profit & Loss PDF.
    Sections: Revenue → Other Income → COGS → Operating Expenses → Finance Costs → Tax → Net Profit
    data keys: income (dict), expenses (dict), total_income (float), total_expenses (float), net_profit (float)
    """
    cn    = company_info.get("name", "Your Company")
    addr  = company_info.get("address", "")
    gstin = company_info.get("gstin", "")
    pan   = company_info.get("pan", "")

    headers = ["#", "Account Head", "Category", "Amount (₹)"]
    widths  = [10, 110, 42, 35]
    aligns  = ["center", "left", "left", "right"]

    all_rows: List[dict] = []
    idx = 1

    # Revenue section
    all_rows.append({"cells": ["", "REVENUE", "", ""], "row_type": "subtotal"})
    income = data.get("income", {})
    for k, v in income.items():
        all_rows.append({"cells": [str(idx), k, "Income", _indian_number(v)], "row_type": ""})
        idx += 1

    ti = data.get("total_income", sum(income.values()) if income else 0.0)
    all_rows.append({"cells": ["", "Total Revenue", "", _indian_number(ti)], "row_type": "subtotal"})

    # Expenses section
    all_rows.append({"cells": ["", "EXPENSES", "", ""], "row_type": "subtotal"})
    expenses = data.get("expenses", {})
    for k, v in expenses.items():
        all_rows.append({"cells": [str(idx), k, "Expense", _indian_number(v)], "row_type": ""})
        idx += 1

    te = data.get("total_expenses", sum(expenses.values()) if expenses else 0.0)
    all_rows.append({"cells": ["", "Total Expenses", "", _indian_number(te)], "row_type": "subtotal"})

    # Net Profit — color will be green/red in the cells string
    np_ = data.get("net_profit", ti - te)
    label = "NET PROFIT" if np_ >= 0 else "NET LOSS"
    all_rows.append({"cells": ["", label, "", _indian_number(np_)], "row_type": "closing"})

    return pdf_build_pages(
        cn, addr, gstin, pan, "Profit & Loss Statement", date_from, date_to,
        headers, all_rows, widths, aligns,
    )


def generate_gst_summary_pdf(
    data: dict,
    company_info: dict,
    date_from: str,
    date_to: str,
) -> bytes:
    """
    GST Summary PDF.
    Tables per type: B2B, B2C Large, B2C Small.
    Columns: Invoice No | Invoice Date | Place of Supply | Taxable Value | CGST | SGST | IGST | Total
    data keys: b2b (list), b2c_large (list), b2c_small (list)
    Each row: invoice_no, invoice_date, place_of_supply, taxable_value, cgst, sgst, igst, total
    """
    cn    = company_info.get("name", "Your Company")
    addr  = company_info.get("address", "")
    gstin = company_info.get("gstin", "")
    pan   = company_info.get("pan", "")

    headers = ["Invoice No", "Date", "Place of Supply", "Taxable Value", "CGST", "SGST", "IGST", "Total"]
    widths  = [28, 20, 30, 28, 20, 20, 20, 28]   # ≈ 194mm
    aligns  = ["left", "center", "left", "right", "right", "right", "right", "right"]

    all_rows: List[dict] = []

    for section_name, section_key in [("B2B Invoices", "b2b"),
                                       ("B2C Large", "b2c_large"),
                                       ("B2C Small", "b2c_small")]:
        items = data.get(section_key, [])
        if not items:
            continue
        all_rows.append({"cells": [section_name, "", "", "", "", "", "", ""], "row_type": "subtotal"})
        for r in items:
            all_rows.append({
                "cells": [
                    r.get("invoice_no", ""),
                    r.get("invoice_date", ""),
                    r.get("place_of_supply", ""),
                    _indian_number(r.get("taxable_value", 0)),
                    _indian_number(r.get("cgst", 0)),
                    _indian_number(r.get("sgst", 0)),
                    _indian_number(r.get("igst", 0)),
                    _indian_number(r.get("total", 0)),
                ],
                "row_type": "",
            })

    if not all_rows:
        all_rows.append({"cells": ["No data available", "", "", "", "", "", "", ""], "row_type": ""})

    return pdf_build_pages(
        cn, addr, gstin, pan, "GST Summary Report", date_from, date_to,
        headers, all_rows, widths, aligns,
    )


def generate_aging_pdf(
    data: dict,
    company_info: dict,
    date_from: str,
    date_to: str,
) -> bytes:
    """
    AR/AP Aging PDF.
    Columns: Party Name | 0-30 | 31-60 | 61-90 | 91-180 | 180+ | Total Outstanding
    Bottom row: Grand Total (closing style).
    data keys: rows (list), totals (dict with same bucket keys)
    Each row: party_name, bucket_0_30, bucket_31_60, bucket_61_90, bucket_91_180, bucket_180plus, total
    """
    cn    = company_info.get("name", "Your Company")
    addr  = company_info.get("address", "")
    gstin = company_info.get("gstin", "")
    pan   = company_info.get("pan", "")

    headers = ["Party Name", "0-30 days", "31-60 days", "61-90 days", "91-180 days", "180+ days", "Total Outstanding"]
    widths  = [55, 22, 22, 22, 22, 22, 30]   # ≈ 195mm
    aligns  = ["left", "right", "right", "right", "right", "right", "right"]

    all_rows: List[dict] = []
    g0_30 = g31_60 = g61_90 = g91_180 = g180p = g_total = 0.0

    for r in data.get("rows", []):
        b0   = r.get("bucket_0_30", 0.0) or 0.0
        b31  = r.get("bucket_31_60", 0.0) or 0.0
        b61  = r.get("bucket_61_90", 0.0) or 0.0
        b91  = r.get("bucket_91_180", 0.0) or 0.0
        b180 = r.get("bucket_180plus", 0.0) or 0.0
        tot  = r.get("total", b0 + b31 + b61 + b91 + b180)
        g0_30 += b0; g31_60 += b31; g61_90 += b61; g91_180 += b91; g180p += b180; g_total += tot
        all_rows.append({
            "cells": [
                r.get("party_name", ""),
                _indian_number(b0),
                _indian_number(b31),
                _indian_number(b61),
                _indian_number(b91),
                _indian_number(b180),
                _indian_number(tot),
            ],
            "row_type": "",
        })

    # Grand total row
    all_rows.append({
        "cells": [
            "GRAND TOTAL",
            _indian_number(g0_30),
            _indian_number(g31_60),
            _indian_number(g61_90),
            _indian_number(g91_180),
            _indian_number(g180p),
            _indian_number(g_total),
        ],
        "row_type": "closing",
    })

    return pdf_build_pages(
        cn, addr, gstin, pan, "AR/AP Aging Report", date_from, date_to,
        headers, all_rows, widths, aligns,
    )


# ══════════════════════════════════════════════════════════════════════════════
# 5 REPORT TEMPLATES — EXCEL
# ══════════════════════════════════════════════════════════════════════════════

def generate_ledger_excel(
    data: dict,
    company_info: dict,
    date_from: str,
    date_to: str,
) -> bytes:
    """Ledger Statement Excel."""
    cn   = company_info.get("name", data.get("company", "Your Company"))
    period = f"{date_from} — {date_to}"
    headers = ["Date", "Particulars", "Voucher Type", "Voucher No", "Debit (₹)", "Credit (₹)", "Balance (₹)"]
    aligns  = ["center", "left", "left", "center", "right", "right", "right"]

    rows: List[dict] = []
    ob = data.get("opening_balance", 0.0)
    rows.append({"cells": ["", "Opening Balance", "", "", "", "", ob], "row_type": "opening"})

    balance = ob
    for r in data.get("rows", []):
        dr = r.get("debit", 0.0) or 0.0
        cr = r.get("credit", 0.0) or 0.0
        balance += dr - cr
        rows.append({
            "cells": [
                r.get("date", ""),
                r.get("particulars", r.get("party_name", "")),
                r.get("voucher_type", ""),
                r.get("voucher_no", r.get("voucher_number", "")),
                dr if dr else None,
                cr if cr else None,
                balance,
            ],
            "row_type": "",
        })

    rows.append({"cells": ["", "Closing Balance", "", "", "", "", balance], "row_type": "closing"})
    return excel_build_workbook(cn, "Ledger Statement", period, headers, rows, aligns, "Ledger")


def generate_balance_sheet_excel(
    data: dict,
    company_info: dict,
    date_from: str,
    date_to: str,
) -> bytes:
    """Balance Sheet Excel."""
    cn     = company_info.get("name", "Your Company")
    period = f"{date_from} — {date_to}"
    headers = ["#", "Ledger / Group", "Section", "Amount (₹)"]
    aligns  = ["center", "left", "left", "right"]

    rows: List[dict] = []
    rows.append({"cells": ["", "ASSETS", "", ""], "row_type": "subtotal"})
    for idx, item in enumerate(data.get("assets", []), 1):
        rows.append({"cells": [idx, item.get("name", ""), item.get("group", ""), item.get("amount", 0)], "row_type": ""})
    rows.append({"cells": ["", "Total Assets", "", data.get("total_assets", 0.0)], "row_type": "closing"})

    rows.append({"cells": ["", "EQUITY & LIABILITIES", "", ""], "row_type": "subtotal"})
    for idx, item in enumerate(data.get("liabilities", []), 1):
        rows.append({"cells": [idx, item.get("name", ""), item.get("group", ""), item.get("amount", 0)], "row_type": ""})
    rows.append({"cells": ["", "Total Equity & Liabilities", "", data.get("total_liabilities", 0.0)], "row_type": "closing"})

    return excel_build_workbook(cn, "Balance Sheet", period, headers, rows, aligns, "Balance Sheet")


def generate_profit_loss_excel(
    data: dict,
    company_info: dict,
    date_from: str,
    date_to: str,
) -> bytes:
    """Profit & Loss Excel."""
    cn     = company_info.get("name", "Your Company")
    period = f"{date_from} — {date_to}"
    headers = ["#", "Account Head", "Category", "Amount (₹)"]
    aligns  = ["center", "left", "left", "right"]

    rows: List[dict] = []
    idx = 1

    rows.append({"cells": ["", "REVENUE", "", ""], "row_type": "subtotal"})
    income = data.get("income", {})
    for k, v in income.items():
        rows.append({"cells": [idx, k, "Income", v], "row_type": ""}); idx += 1
    ti = data.get("total_income", sum(income.values()) if income else 0.0)
    rows.append({"cells": ["", "Total Revenue", "", ti], "row_type": "subtotal"})

    rows.append({"cells": ["", "EXPENSES", "", ""], "row_type": "subtotal"})
    expenses = data.get("expenses", {})
    for k, v in expenses.items():
        rows.append({"cells": [idx, k, "Expense", v], "row_type": ""}); idx += 1
    te = data.get("total_expenses", sum(expenses.values()) if expenses else 0.0)
    rows.append({"cells": ["", "Total Expenses", "", te], "row_type": "subtotal"})

    np_ = data.get("net_profit", ti - te)
    label = "NET PROFIT" if np_ >= 0 else "NET LOSS"
    rows.append({"cells": ["", label, "", np_], "row_type": "closing"})

    return excel_build_workbook(cn, "Profit & Loss", period, headers, rows, aligns, "P&L")


def generate_gst_summary_excel(
    data: dict,
    company_info: dict,
    date_from: str,
    date_to: str,
) -> bytes:
    """GST Summary Excel."""
    cn     = company_info.get("name", "Your Company")
    period = f"{date_from} — {date_to}"
    headers = ["Invoice No", "Date", "Place of Supply", "Taxable Value", "CGST", "SGST", "IGST", "Total"]
    aligns  = ["left", "center", "left", "right", "right", "right", "right", "right"]

    rows: List[dict] = []
    for section_name, section_key in [("B2B Invoices", "b2b"),
                                       ("B2C Large", "b2c_large"),
                                       ("B2C Small", "b2c_small")]:
        items = data.get(section_key, [])
        if not items:
            continue
        rows.append({"cells": [section_name, "", "", "", "", "", "", ""], "row_type": "subtotal"})
        for r in items:
            rows.append({
                "cells": [
                    r.get("invoice_no", ""),
                    r.get("invoice_date", ""),
                    r.get("place_of_supply", ""),
                    r.get("taxable_value", 0),
                    r.get("cgst", 0),
                    r.get("sgst", 0),
                    r.get("igst", 0),
                    r.get("total", 0),
                ],
                "row_type": "",
            })

    if not rows:
        rows.append({"cells": ["No data", "", "", 0, 0, 0, 0, 0], "row_type": ""})

    return excel_build_workbook(cn, "GST Summary", period, headers, rows, aligns, "GST Summary")


def generate_aging_excel(
    data: dict,
    company_info: dict,
    date_from: str,
    date_to: str,
) -> bytes:
    """AR/AP Aging Excel."""
    cn     = company_info.get("name", "Your Company")
    period = f"{date_from} — {date_to}"
    headers = ["Party Name", "0-30 days", "31-60 days", "61-90 days", "91-180 days", "180+ days", "Total Outstanding"]
    aligns  = ["left", "right", "right", "right", "right", "right", "right"]

    rows: List[dict] = []
    g = [0.0] * 7

    for r in data.get("rows", []):
        b0   = r.get("bucket_0_30", 0.0) or 0.0
        b31  = r.get("bucket_31_60", 0.0) or 0.0
        b61  = r.get("bucket_61_90", 0.0) or 0.0
        b91  = r.get("bucket_91_180", 0.0) or 0.0
        b180 = r.get("bucket_180plus", 0.0) or 0.0
        tot  = r.get("total", b0 + b31 + b61 + b91 + b180)
        for gi, val in enumerate([0, b0, b31, b61, b91, b180, tot]):
            g[gi] += val
        rows.append({"cells": [r.get("party_name", ""), b0, b31, b61, b91, b180, tot], "row_type": ""})

    rows.append({
        "cells": ["GRAND TOTAL", g[1], g[2], g[3], g[4], g[5], g[6]],
        "row_type": "closing",
    })

    return excel_build_workbook(cn, "AR/AP Aging", period, headers, rows, aligns, "Aging")
