/**
 * K24 PDF Export Utility
 * ------------------------
 * A global, reusable PDF generator for all financial reports.
 * Uses jsPDF + jspdf-autotable for professional output.
 *
 * Template Design:
 * ┌─────────────────────────────────────────────────────────────┐
 * │  K24 Intelligence ERP            [Right: Company Name]      │
 * │  ─────────────────────────────────────────────────────────  │
 * │  SALES REGISTER                  Period: 01 Apr – 31 Mar    │
 * ├─────────────────────────────────────────────────────────────┤
 * │  Total ₹X,XX,XX,XXX   Transactions: 42   Est. Tax: ₹XX,XXX │
 * ├─────────────────────────────────────────────────────────────┤
 * │  Date  │ Party Name │ Type │ Vch No. │ Amount               │
 * │  ...rows...                                                  │
 * ├─────────────────────────────────────────────────────────────┤
 * │  Generated by K24 on 21-Feb-2026 13:17  CONFIDENTIAL        │
 * └─────────────────────────────────────────────────────────────┘
 */

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// ─── Colours (matches app design) ─────────────────────────────────────────────
const COLORS = {
    primary: [15, 23, 42] as [number, number, number],        // slate-900
    accent: [59, 130, 246] as [number, number, number],       // blue-500
    muted: [100, 116, 139] as [number, number, number],       // slate-500
    border: [226, 232, 240] as [number, number, number],      // slate-200
    white: [255, 255, 255] as [number, number, number],
    rowAlt: [248, 250, 252] as [number, number, number],      // slate-50
    green: [22, 163, 74] as [number, number, number],
    red: [220, 38, 38] as [number, number, number],
};

export interface ExportColumn {
    header: string;
    dataKey: string;
    align?: "left" | "right" | "center";
    isAmount?: boolean;
}

export interface ExportSummaryItem {
    label: string;
    value: string;
}

export interface ExportOptions {
    title: string;                    // e.g. "Sales Register"
    subtitle?: string;                // e.g. "FY 2025-26"
    period?: string;                  // e.g. "01 Apr 2025 – 31 Mar 2026"
    companyName?: string;             // e.g. "ABC Technologies Pvt. Ltd."
    summary?: ExportSummaryItem[];    // KPI strip at top of data
    columns: ExportColumn[];
    rows: Record<string, any>[];
    filename?: string;
}

function formatINR(val: any): string {
    const num = parseFloat(val);
    if (isNaN(num)) return String(val ?? "—");
    return `₹${Math.abs(num).toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
}

function formatCell(val: any, col: ExportColumn): string {
    if (val === null || val === undefined) return "—";
    if (col.isAmount) return formatINR(val);
    return String(val);
}

export function exportToPDF(options: ExportOptions): void {
    const {
        title,
        subtitle = "",
        period = "",
        companyName = "Your Company",
        summary = [],
        columns,
        rows,
        filename,
    } = options;

    const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();
    const margin = 14;
    let y = margin;

    // ── HEADER BAND ───────────────────────────────────────────────────────────
    // Top blue bar
    doc.setFillColor(...COLORS.accent);
    doc.rect(0, 0, pageW, 14, "F");

    // App branding (left)
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.white);
    doc.text("K24 INTELLIGENCE ERP", margin, 9);

    // Company name (right)
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(companyName.toUpperCase(), pageW - margin, 9, { align: "right" });

    y = 20;

    // Report title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(...COLORS.primary);
    doc.text(title.toUpperCase(), margin, y);

    // Subtitle + period (right)
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.muted);
    if (subtitle) doc.text(subtitle, pageW - margin, y - 4, { align: "right" });
    if (period) doc.text(`Period: ${period}`, pageW - margin, y + 2, { align: "right" });

    y += 6;

    // Thin divider
    doc.setDrawColor(...COLORS.border);
    doc.setLineWidth(0.4);
    doc.line(margin, y, pageW - margin, y);

    y += 6;

    // ── KPI SUMMARY STRIP ────────────────────────────────────────────────────
    if (summary.length > 0) {
        const boxW = (pageW - margin * 2) / summary.length;
        const boxH = 14;

        summary.forEach((item, i) => {
            const x = margin + i * boxW;

            // Card background
            doc.setFillColor(...COLORS.rowAlt);
            doc.roundedRect(x, y, boxW - 3, boxH, 2, 2, "F");
            doc.setDrawColor(...COLORS.border);
            doc.roundedRect(x, y, boxW - 3, boxH, 2, 2, "D");

            // Label
            doc.setFont("helvetica", "normal");
            doc.setFontSize(7);
            doc.setTextColor(...COLORS.muted);
            doc.text(item.label.toUpperCase(), x + 4, y + 4.5);

            // Value
            doc.setFont("helvetica", "bold");
            doc.setFontSize(10);
            doc.setTextColor(...COLORS.primary);
            doc.text(item.value, x + 4, y + 11);
        });

        y += boxH + 6;
    }

    // ── DATA TABLE ────────────────────────────────────────────────────────────
    const tableColumns = columns.map((col) => ({
        header: col.header,
        dataKey: col.dataKey,
    }));

    const tableRows = rows.map((row) => {
        const r: Record<string, string> = {};
        columns.forEach((col) => {
            r[col.dataKey] = formatCell(row[col.dataKey], col);
        });
        return r;
    });

    autoTable(doc, {
        startY: y,
        head: [tableColumns.map((c) => c.header)],
        body: tableRows.map((row) => tableColumns.map((c) => row[c.dataKey])),
        margin: { left: margin, right: margin },
        tableWidth: pageW - margin * 2,
        styles: {
            font: "helvetica",
            fontSize: 8,
            cellPadding: { top: 3, bottom: 3, left: 4, right: 4 },
            textColor: COLORS.primary,
            lineColor: COLORS.border,
            lineWidth: 0.2,
        },
        headStyles: {
            fillColor: COLORS.primary,
            textColor: COLORS.white,
            fontStyle: "bold",
            fontSize: 7.5,
        },
        alternateRowStyles: {
            fillColor: COLORS.rowAlt,
        },
        columnStyles: (() => {
            const styles: Record<number, any> = {};
            columns.forEach((col, i) => {
                if (col.align === "right" || col.isAmount) {
                    styles[i] = { halign: "right" };
                } else if (col.align === "center") {
                    styles[i] = { halign: "center" };
                }
            });
            return styles;
        })(),
        didDrawPage: (data) => {
            // ── FOOTER on every page ────────────────────────────────────────
            const footerY = pageH - 8;
            doc.setDrawColor(...COLORS.border);
            doc.setLineWidth(0.3);
            doc.line(margin, footerY - 3, pageW - margin, footerY - 3);

            doc.setFont("helvetica", "normal");
            doc.setFontSize(7);
            doc.setTextColor(...COLORS.muted);

            const now = new Date();
            const generated = `Generated by K24 Intelligence ERP on ${now.toLocaleDateString("en-IN", {
                day: "2-digit", month: "short", year: "numeric",
            })} at ${now.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" })}`;

            doc.text(generated, margin, footerY);
            doc.text(
                `CONFIDENTIAL — DO NOT SHARE  |  Page ${(data.pageNumber ?? 1)}`,
                pageW - margin,
                footerY,
                { align: "right" }
            );
        },
    });

    // ── SAVE ─────────────────────────────────────────────────────────────────
    const safeTitle = title.toLowerCase().replace(/\s+/g, "-");
    const dateStr = new Date().toISOString().slice(0, 10);
    doc.save(filename || `k24-${safeTitle}-${dateStr}.pdf`);
}


// ─── Convenience helper for report pages ──────────────────────────────────────
export function exportReportPDF(params: {
    slug: string;
    title: string;
    period: string;
    companyName?: string;
    summary: ExportSummaryItem[];
    columns: ExportColumn[];
    rows: Record<string, any>[];
}) {
    exportToPDF({
        title: params.title,
        subtitle: "K24 Intelligence ERP",
        period: params.period,
        companyName: params.companyName || "Your Company",
        summary: params.summary,
        columns: params.columns,
        rows: params.rows,
        filename: `k24-${params.slug}-${new Date().toISOString().slice(0, 10)}.pdf`,
    });
}
